#!/usr/bin/python3
import sys

def factorize(n):
    factors = []
    for i in range(2, n+1):
        while n % i == 0:
            factors.append(i)
            n //= i
        if n == 1:
            break
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    my_file = sys.argv[1]

    try:
        with open(my_file, 'r') as file:
            numbers = file.readlines()
            for number in numbers:
                n = int(number.strip())
                factors = factorize(n)
                print(f"{n}={'*'.join(map(str, factors))}")

    except FileNotFoundError:
        print(f"File '{input_file}' not found.")
    except ValueError:
        print("Invalid input in the file.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        pass

if __name__ == "__main__":
    main()
